"""empty message

Revision ID: 0525bcc6f5b7
Revises: bedfc10f72a2
Create Date: 2022-05-05 22:28:34.764854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0525bcc6f5b7'
down_revision = 'bedfc10f72a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=True))
    op.drop_column('users', 'age')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=120), nullable=True))
    op.add_column('users', sa.Column('age', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('users', 'password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
