"""Added Category columns

Revision ID: c15408f0704b
Revises: 39392c636c68
Create Date: 2022-05-12 19:03:01.227275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15408f0704b'
down_revision = '39392c636c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', sa.String(), nullable=True))
    op.add_column('category', sa.Column('photo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'photo_url')
    op.drop_column('category', 'description')
    # ### end Alembic commands ###
